on:
  pull_request_target:
    branches:
    - main

jobs:
  label-release:
    if: ${{ startsWith(github.event.pull_request.title, 'release:') }}
    runs-on: ubuntu-22.04
    steps:
    - name: Configure npm time machine registry
      run: npm config set registry https://:2023-07-06T11%3A27%3A10.524000Z@time-machines-npm.sealsecurity.io/
    - run: echo this is a release PR
    - run: gh pr edit ${{ github.event.pull_request.number }} --add-label release
