name: Ensure API Peer Dependency

on:
  push:
    branches:
    - main
    - master
  pull_request:
  merge_group:

jobs:
  peer-api-check:
    runs-on: ubuntu-22.04
    container:
      image: node:20
    steps:
    - name: Configure npm time machine registry
      run: npm config set registry https://:2023-07-06T11%3A27%3A10.524000Z@time-machines-npm.sealsecurity.io/
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install lerna
      run: npm install -g lerna

    - name: Install semver
      run: npm install semver

    - name: Check API dependency semantics
      working-directory: packages
      run: lerna run peer-api-check
